//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP3Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjetoPessoa
    {
        public long ID { get; set; }
        public Nullable<long> IDPROJETO { get; set; }
        public Nullable<long> IDPESSOA { get; set; }
        public Nullable<System.DateTime> DATAINGRESSO { get; set; }
        public string OCUPACAO { get; set; }
        public string OBSERVACOES { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Projeto Projeto { get; set; }
    }
}
